# Generated by Django 5.2 on 2025-05-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
